#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMKMart
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SMKMart")]
	public partial class DatabaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDetailTrx(DetailTrx instance);
    partial void UpdateDetailTrx(DetailTrx instance);
    partial void DeleteDetailTrx(DetailTrx instance);
    partial void InsertPromo(Promo instance);
    partial void UpdatePromo(Promo instance);
    partial void DeletePromo(Promo instance);
    partial void InsertEmployee(Employee instance);
    partial void UpdateEmployee(Employee instance);
    partial void DeleteEmployee(Employee instance);
    partial void InsertHeaderTrx(HeaderTrx instance);
    partial void UpdateHeaderTrx(HeaderTrx instance);
    partial void DeleteHeaderTrx(HeaderTrx instance);
    partial void InsertMember(Member instance);
    partial void UpdateMember(Member instance);
    partial void DeleteMember(Member instance);
    partial void InsertProduk(Produk instance);
    partial void UpdateProduk(Produk instance);
    partial void DeleteProduk(Produk instance);
    #endregion
		
		public DatabaseDataContext() : 
				base(global::SMKMart.Properties.Settings.Default.SMKMartConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DetailTrx> DetailTrxes
		{
			get
			{
				return this.GetTable<DetailTrx>();
			}
		}
		
		public System.Data.Linq.Table<Promo> Promos
		{
			get
			{
				return this.GetTable<Promo>();
			}
		}
		
		public System.Data.Linq.Table<Employee> Employees
		{
			get
			{
				return this.GetTable<Employee>();
			}
		}
		
		public System.Data.Linq.Table<HeaderTrx> HeaderTrxes
		{
			get
			{
				return this.GetTable<HeaderTrx>();
			}
		}
		
		public System.Data.Linq.Table<Member> Members
		{
			get
			{
				return this.GetTable<Member>();
			}
		}
		
		public System.Data.Linq.Table<Produk> Produks
		{
			get
			{
				return this.GetTable<Produk>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DetailTrx")]
	public partial class DetailTrx : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DetailTrxId;
		
		private string _TrxId;
		
		private string _ProdukId;
		
		private int _Qty;
		
		private int _BuyPrice;
		
		private int _SellPrice;
		
		private System.Nullable<int> _PromoId;
		
		private EntityRef<Promo> _Promo;
		
		private EntityRef<HeaderTrx> _HeaderTrx;
		
		private EntityRef<Produk> _Produk;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDetailTrxIdChanging(int value);
    partial void OnDetailTrxIdChanged();
    partial void OnTrxIdChanging(string value);
    partial void OnTrxIdChanged();
    partial void OnProdukIdChanging(string value);
    partial void OnProdukIdChanged();
    partial void OnQtyChanging(int value);
    partial void OnQtyChanged();
    partial void OnBuyPriceChanging(int value);
    partial void OnBuyPriceChanged();
    partial void OnSellPriceChanging(int value);
    partial void OnSellPriceChanged();
    partial void OnPromoIdChanging(System.Nullable<int> value);
    partial void OnPromoIdChanged();
    #endregion
		
		public DetailTrx()
		{
			this._Promo = default(EntityRef<Promo>);
			this._HeaderTrx = default(EntityRef<HeaderTrx>);
			this._Produk = default(EntityRef<Produk>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetailTrxId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int DetailTrxId
		{
			get
			{
				return this._DetailTrxId;
			}
			set
			{
				if ((this._DetailTrxId != value))
				{
					this.OnDetailTrxIdChanging(value);
					this.SendPropertyChanging();
					this._DetailTrxId = value;
					this.SendPropertyChanged("DetailTrxId");
					this.OnDetailTrxIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrxId", DbType="NChar(11) NOT NULL", CanBeNull=false)]
		public string TrxId
		{
			get
			{
				return this._TrxId;
			}
			set
			{
				if ((this._TrxId != value))
				{
					if (this._HeaderTrx.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTrxIdChanging(value);
					this.SendPropertyChanging();
					this._TrxId = value;
					this.SendPropertyChanged("TrxId");
					this.OnTrxIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProdukId", DbType="NChar(6) NOT NULL", CanBeNull=false)]
		public string ProdukId
		{
			get
			{
				return this._ProdukId;
			}
			set
			{
				if ((this._ProdukId != value))
				{
					if (this._Produk.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProdukIdChanging(value);
					this.SendPropertyChanging();
					this._ProdukId = value;
					this.SendPropertyChanged("ProdukId");
					this.OnProdukIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Qty", DbType="Int NOT NULL")]
		public int Qty
		{
			get
			{
				return this._Qty;
			}
			set
			{
				if ((this._Qty != value))
				{
					this.OnQtyChanging(value);
					this.SendPropertyChanging();
					this._Qty = value;
					this.SendPropertyChanged("Qty");
					this.OnQtyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BuyPrice", DbType="Int NOT NULL")]
		public int BuyPrice
		{
			get
			{
				return this._BuyPrice;
			}
			set
			{
				if ((this._BuyPrice != value))
				{
					this.OnBuyPriceChanging(value);
					this.SendPropertyChanging();
					this._BuyPrice = value;
					this.SendPropertyChanged("BuyPrice");
					this.OnBuyPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SellPrice", DbType="Int NOT NULL")]
		public int SellPrice
		{
			get
			{
				return this._SellPrice;
			}
			set
			{
				if ((this._SellPrice != value))
				{
					this.OnSellPriceChanging(value);
					this.SendPropertyChanging();
					this._SellPrice = value;
					this.SendPropertyChanged("SellPrice");
					this.OnSellPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PromoId", DbType="Int")]
		public System.Nullable<int> PromoId
		{
			get
			{
				return this._PromoId;
			}
			set
			{
				if ((this._PromoId != value))
				{
					if (this._Promo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPromoIdChanging(value);
					this.SendPropertyChanging();
					this._PromoId = value;
					this.SendPropertyChanged("PromoId");
					this.OnPromoIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Promo_DetailTrx", Storage="_Promo", ThisKey="PromoId", OtherKey="PromoId", IsForeignKey=true)]
		public Promo Promo
		{
			get
			{
				return this._Promo.Entity;
			}
			set
			{
				Promo previousValue = this._Promo.Entity;
				if (((previousValue != value) 
							|| (this._Promo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Promo.Entity = null;
						previousValue.DetailTrxes.Remove(this);
					}
					this._Promo.Entity = value;
					if ((value != null))
					{
						value.DetailTrxes.Add(this);
						this._PromoId = value.PromoId;
					}
					else
					{
						this._PromoId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Promo");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HeaderTrx_DetailTrx", Storage="_HeaderTrx", ThisKey="TrxId", OtherKey="TrxId", IsForeignKey=true)]
		public HeaderTrx HeaderTrx
		{
			get
			{
				return this._HeaderTrx.Entity;
			}
			set
			{
				HeaderTrx previousValue = this._HeaderTrx.Entity;
				if (((previousValue != value) 
							|| (this._HeaderTrx.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HeaderTrx.Entity = null;
						previousValue.DetailTrxes.Remove(this);
					}
					this._HeaderTrx.Entity = value;
					if ((value != null))
					{
						value.DetailTrxes.Add(this);
						this._TrxId = value.TrxId;
					}
					else
					{
						this._TrxId = default(string);
					}
					this.SendPropertyChanged("HeaderTrx");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Produk_DetailTrx", Storage="_Produk", ThisKey="ProdukId", OtherKey="ProdukId", IsForeignKey=true)]
		public Produk Produk
		{
			get
			{
				return this._Produk.Entity;
			}
			set
			{
				Produk previousValue = this._Produk.Entity;
				if (((previousValue != value) 
							|| (this._Produk.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Produk.Entity = null;
						previousValue.DetailTrxes.Remove(this);
					}
					this._Produk.Entity = value;
					if ((value != null))
					{
						value.DetailTrxes.Add(this);
						this._ProdukId = value.ProdukId;
					}
					else
					{
						this._ProdukId = default(string);
					}
					this.SendPropertyChanged("Produk");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Promo")]
	public partial class Promo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PromoId;
		
		private string _ProdukId;
		
		private System.Nullable<int> _BuyQty;
		
		private string _Type;
		
		private System.Nullable<int> _Reward;
		
		private System.Nullable<System.DateTime> _StartDate;
		
		private System.Nullable<System.DateTime> _EndDate;
		
		private EntitySet<DetailTrx> _DetailTrxes;
		
		private EntityRef<Produk> _Produk;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPromoIdChanging(int value);
    partial void OnPromoIdChanged();
    partial void OnProdukIdChanging(string value);
    partial void OnProdukIdChanged();
    partial void OnBuyQtyChanging(System.Nullable<int> value);
    partial void OnBuyQtyChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    partial void OnRewardChanging(System.Nullable<int> value);
    partial void OnRewardChanged();
    partial void OnStartDateChanging(System.Nullable<System.DateTime> value);
    partial void OnStartDateChanged();
    partial void OnEndDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEndDateChanged();
    #endregion
		
		public Promo()
		{
			this._DetailTrxes = new EntitySet<DetailTrx>(new Action<DetailTrx>(this.attach_DetailTrxes), new Action<DetailTrx>(this.detach_DetailTrxes));
			this._Produk = default(EntityRef<Produk>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PromoId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PromoId
		{
			get
			{
				return this._PromoId;
			}
			set
			{
				if ((this._PromoId != value))
				{
					this.OnPromoIdChanging(value);
					this.SendPropertyChanging();
					this._PromoId = value;
					this.SendPropertyChanged("PromoId");
					this.OnPromoIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProdukId", DbType="NChar(6)")]
		public string ProdukId
		{
			get
			{
				return this._ProdukId;
			}
			set
			{
				if ((this._ProdukId != value))
				{
					if (this._Produk.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProdukIdChanging(value);
					this.SendPropertyChanging();
					this._ProdukId = value;
					this.SendPropertyChanged("ProdukId");
					this.OnProdukIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BuyQty", DbType="Int")]
		public System.Nullable<int> BuyQty
		{
			get
			{
				return this._BuyQty;
			}
			set
			{
				if ((this._BuyQty != value))
				{
					this.OnBuyQtyChanging(value);
					this.SendPropertyChanging();
					this._BuyQty = value;
					this.SendPropertyChanged("BuyQty");
					this.OnBuyQtyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="NVarChar(50)")]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reward", DbType="Int")]
		public System.Nullable<int> Reward
		{
			get
			{
				return this._Reward;
			}
			set
			{
				if ((this._Reward != value))
				{
					this.OnRewardChanging(value);
					this.SendPropertyChanging();
					this._Reward = value;
					this.SendPropertyChanged("Reward");
					this.OnRewardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDate", DbType="Date")]
		public System.Nullable<System.DateTime> StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				if ((this._StartDate != value))
				{
					this.OnStartDateChanging(value);
					this.SendPropertyChanging();
					this._StartDate = value;
					this.SendPropertyChanged("StartDate");
					this.OnStartDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDate", DbType="Date")]
		public System.Nullable<System.DateTime> EndDate
		{
			get
			{
				return this._EndDate;
			}
			set
			{
				if ((this._EndDate != value))
				{
					this.OnEndDateChanging(value);
					this.SendPropertyChanging();
					this._EndDate = value;
					this.SendPropertyChanged("EndDate");
					this.OnEndDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Promo_DetailTrx", Storage="_DetailTrxes", ThisKey="PromoId", OtherKey="PromoId")]
		public EntitySet<DetailTrx> DetailTrxes
		{
			get
			{
				return this._DetailTrxes;
			}
			set
			{
				this._DetailTrxes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Produk_Promo", Storage="_Produk", ThisKey="ProdukId", OtherKey="ProdukId", IsForeignKey=true)]
		public Produk Produk
		{
			get
			{
				return this._Produk.Entity;
			}
			set
			{
				Produk previousValue = this._Produk.Entity;
				if (((previousValue != value) 
							|| (this._Produk.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Produk.Entity = null;
						previousValue.Promos.Remove(this);
					}
					this._Produk.Entity = value;
					if ((value != null))
					{
						value.Promos.Add(this);
						this._ProdukId = value.ProdukId;
					}
					else
					{
						this._ProdukId = default(string);
					}
					this.SendPropertyChanged("Produk");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DetailTrxes(DetailTrx entity)
		{
			this.SendPropertyChanging();
			entity.Promo = this;
		}
		
		private void detach_DetailTrxes(DetailTrx entity)
		{
			this.SendPropertyChanging();
			entity.Promo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Employee")]
	public partial class Employee : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _EmployeeID;
		
		private string _Name;
		
		private string _Position;
		
		private string _Email;
		
		private string _Password;
		
		private string _Handphone;
		
		private System.Nullable<System.DateTime> _Birthdate;
		
		private EntitySet<HeaderTrx> _HeaderTrxes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEmployeeIDChanging(int value);
    partial void OnEmployeeIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnPositionChanging(string value);
    partial void OnPositionChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnHandphoneChanging(string value);
    partial void OnHandphoneChanged();
    partial void OnBirthdateChanging(System.Nullable<System.DateTime> value);
    partial void OnBirthdateChanged();
    #endregion
		
		public Employee()
		{
			this._HeaderTrxes = new EntitySet<HeaderTrx>(new Action<HeaderTrx>(this.attach_HeaderTrxes), new Action<HeaderTrx>(this.detach_HeaderTrxes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int EmployeeID
		{
			get
			{
				return this._EmployeeID;
			}
			set
			{
				if ((this._EmployeeID != value))
				{
					this.OnEmployeeIDChanging(value);
					this.SendPropertyChanging();
					this._EmployeeID = value;
					this.SendPropertyChanged("EmployeeID");
					this.OnEmployeeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Position", DbType="NVarChar(50)")]
		public string Position
		{
			get
			{
				return this._Position;
			}
			set
			{
				if ((this._Position != value))
				{
					this.OnPositionChanging(value);
					this.SendPropertyChanging();
					this._Position = value;
					this.SendPropertyChanged("Position");
					this.OnPositionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Handphone", DbType="NVarChar(13)")]
		public string Handphone
		{
			get
			{
				return this._Handphone;
			}
			set
			{
				if ((this._Handphone != value))
				{
					this.OnHandphoneChanging(value);
					this.SendPropertyChanging();
					this._Handphone = value;
					this.SendPropertyChanged("Handphone");
					this.OnHandphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Birthdate", DbType="Date")]
		public System.Nullable<System.DateTime> Birthdate
		{
			get
			{
				return this._Birthdate;
			}
			set
			{
				if ((this._Birthdate != value))
				{
					this.OnBirthdateChanging(value);
					this.SendPropertyChanging();
					this._Birthdate = value;
					this.SendPropertyChanged("Birthdate");
					this.OnBirthdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Employee_HeaderTrx", Storage="_HeaderTrxes", ThisKey="EmployeeID", OtherKey="EmployeeId")]
		public EntitySet<HeaderTrx> HeaderTrxes
		{
			get
			{
				return this._HeaderTrxes;
			}
			set
			{
				this._HeaderTrxes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HeaderTrxes(HeaderTrx entity)
		{
			this.SendPropertyChanging();
			entity.Employee = this;
		}
		
		private void detach_HeaderTrxes(HeaderTrx entity)
		{
			this.SendPropertyChanging();
			entity.Employee = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HeaderTrx")]
	public partial class HeaderTrx : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TrxId;
		
		private System.DateTime _Date;
		
		private int _EmployeeId;
		
		private string _MemberId;
		
		private EntitySet<DetailTrx> _DetailTrxes;
		
		private EntityRef<Employee> _Employee;
		
		private EntityRef<Member> _Member;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTrxIdChanging(string value);
    partial void OnTrxIdChanged();
    partial void OnDateChanging(System.DateTime value);
    partial void OnDateChanged();
    partial void OnEmployeeIdChanging(int value);
    partial void OnEmployeeIdChanged();
    partial void OnMemberIdChanging(string value);
    partial void OnMemberIdChanged();
    #endregion
		
		public HeaderTrx()
		{
			this._DetailTrxes = new EntitySet<DetailTrx>(new Action<DetailTrx>(this.attach_DetailTrxes), new Action<DetailTrx>(this.detach_DetailTrxes));
			this._Employee = default(EntityRef<Employee>);
			this._Member = default(EntityRef<Member>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrxId", DbType="NChar(11) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TrxId
		{
			get
			{
				return this._TrxId;
			}
			set
			{
				if ((this._TrxId != value))
				{
					this.OnTrxIdChanging(value);
					this.SendPropertyChanging();
					this._TrxId = value;
					this.SendPropertyChanged("TrxId");
					this.OnTrxIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeId", DbType="Int NOT NULL")]
		public int EmployeeId
		{
			get
			{
				return this._EmployeeId;
			}
			set
			{
				if ((this._EmployeeId != value))
				{
					if (this._Employee.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEmployeeIdChanging(value);
					this.SendPropertyChanging();
					this._EmployeeId = value;
					this.SendPropertyChanged("EmployeeId");
					this.OnEmployeeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberId", DbType="NChar(10)")]
		public string MemberId
		{
			get
			{
				return this._MemberId;
			}
			set
			{
				if ((this._MemberId != value))
				{
					if (this._Member.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMemberIdChanging(value);
					this.SendPropertyChanging();
					this._MemberId = value;
					this.SendPropertyChanged("MemberId");
					this.OnMemberIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HeaderTrx_DetailTrx", Storage="_DetailTrxes", ThisKey="TrxId", OtherKey="TrxId")]
		public EntitySet<DetailTrx> DetailTrxes
		{
			get
			{
				return this._DetailTrxes;
			}
			set
			{
				this._DetailTrxes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Employee_HeaderTrx", Storage="_Employee", ThisKey="EmployeeId", OtherKey="EmployeeID", IsForeignKey=true)]
		public Employee Employee
		{
			get
			{
				return this._Employee.Entity;
			}
			set
			{
				Employee previousValue = this._Employee.Entity;
				if (((previousValue != value) 
							|| (this._Employee.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Employee.Entity = null;
						previousValue.HeaderTrxes.Remove(this);
					}
					this._Employee.Entity = value;
					if ((value != null))
					{
						value.HeaderTrxes.Add(this);
						this._EmployeeId = value.EmployeeID;
					}
					else
					{
						this._EmployeeId = default(int);
					}
					this.SendPropertyChanged("Employee");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Member_HeaderTrx", Storage="_Member", ThisKey="MemberId", OtherKey="MemberId", IsForeignKey=true)]
		public Member Member
		{
			get
			{
				return this._Member.Entity;
			}
			set
			{
				Member previousValue = this._Member.Entity;
				if (((previousValue != value) 
							|| (this._Member.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Member.Entity = null;
						previousValue.HeaderTrxes.Remove(this);
					}
					this._Member.Entity = value;
					if ((value != null))
					{
						value.HeaderTrxes.Add(this);
						this._MemberId = value.MemberId;
					}
					else
					{
						this._MemberId = default(string);
					}
					this.SendPropertyChanged("Member");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DetailTrxes(DetailTrx entity)
		{
			this.SendPropertyChanging();
			entity.HeaderTrx = this;
		}
		
		private void detach_DetailTrxes(DetailTrx entity)
		{
			this.SendPropertyChanging();
			entity.HeaderTrx = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Member")]
	public partial class Member : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MemberId;
		
		private string _Name;
		
		private string _Email;
		
		private string _Handphone;
		
		private System.Nullable<System.DateTime> _Expired;
		
		private EntitySet<HeaderTrx> _HeaderTrxes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMemberIdChanging(string value);
    partial void OnMemberIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnHandphoneChanging(string value);
    partial void OnHandphoneChanged();
    partial void OnExpiredChanging(System.Nullable<System.DateTime> value);
    partial void OnExpiredChanged();
    #endregion
		
		public Member()
		{
			this._HeaderTrxes = new EntitySet<HeaderTrx>(new Action<HeaderTrx>(this.attach_HeaderTrxes), new Action<HeaderTrx>(this.detach_HeaderTrxes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberId", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MemberId
		{
			get
			{
				return this._MemberId;
			}
			set
			{
				if ((this._MemberId != value))
				{
					this.OnMemberIdChanging(value);
					this.SendPropertyChanging();
					this._MemberId = value;
					this.SendPropertyChanged("MemberId");
					this.OnMemberIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Handphone", DbType="NVarChar(12)")]
		public string Handphone
		{
			get
			{
				return this._Handphone;
			}
			set
			{
				if ((this._Handphone != value))
				{
					this.OnHandphoneChanging(value);
					this.SendPropertyChanging();
					this._Handphone = value;
					this.SendPropertyChanged("Handphone");
					this.OnHandphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expired", DbType="Date")]
		public System.Nullable<System.DateTime> Expired
		{
			get
			{
				return this._Expired;
			}
			set
			{
				if ((this._Expired != value))
				{
					this.OnExpiredChanging(value);
					this.SendPropertyChanging();
					this._Expired = value;
					this.SendPropertyChanged("Expired");
					this.OnExpiredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Member_HeaderTrx", Storage="_HeaderTrxes", ThisKey="MemberId", OtherKey="MemberId")]
		public EntitySet<HeaderTrx> HeaderTrxes
		{
			get
			{
				return this._HeaderTrxes;
			}
			set
			{
				this._HeaderTrxes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HeaderTrxes(HeaderTrx entity)
		{
			this.SendPropertyChanging();
			entity.Member = this;
		}
		
		private void detach_HeaderTrxes(HeaderTrx entity)
		{
			this.SendPropertyChanging();
			entity.Member = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Produk")]
	public partial class Produk : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ProdukId;
		
		private string _Name;
		
		private string _Specification;
		
		private System.Nullable<int> _BuyPrice;
		
		private System.Nullable<int> _SellPrice;
		
		private EntitySet<DetailTrx> _DetailTrxes;
		
		private EntitySet<Promo> _Promos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProdukIdChanging(string value);
    partial void OnProdukIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnSpecificationChanging(string value);
    partial void OnSpecificationChanged();
    partial void OnBuyPriceChanging(System.Nullable<int> value);
    partial void OnBuyPriceChanged();
    partial void OnSellPriceChanging(System.Nullable<int> value);
    partial void OnSellPriceChanged();
    #endregion
		
		public Produk()
		{
			this._DetailTrxes = new EntitySet<DetailTrx>(new Action<DetailTrx>(this.attach_DetailTrxes), new Action<DetailTrx>(this.detach_DetailTrxes));
			this._Promos = new EntitySet<Promo>(new Action<Promo>(this.attach_Promos), new Action<Promo>(this.detach_Promos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProdukId", DbType="NChar(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ProdukId
		{
			get
			{
				return this._ProdukId;
			}
			set
			{
				if ((this._ProdukId != value))
				{
					this.OnProdukIdChanging(value);
					this.SendPropertyChanging();
					this._ProdukId = value;
					this.SendPropertyChanged("ProdukId");
					this.OnProdukIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Specification", DbType="NVarChar(50)")]
		public string Specification
		{
			get
			{
				return this._Specification;
			}
			set
			{
				if ((this._Specification != value))
				{
					this.OnSpecificationChanging(value);
					this.SendPropertyChanging();
					this._Specification = value;
					this.SendPropertyChanged("Specification");
					this.OnSpecificationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BuyPrice", DbType="Int")]
		public System.Nullable<int> BuyPrice
		{
			get
			{
				return this._BuyPrice;
			}
			set
			{
				if ((this._BuyPrice != value))
				{
					this.OnBuyPriceChanging(value);
					this.SendPropertyChanging();
					this._BuyPrice = value;
					this.SendPropertyChanged("BuyPrice");
					this.OnBuyPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SellPrice", DbType="Int")]
		public System.Nullable<int> SellPrice
		{
			get
			{
				return this._SellPrice;
			}
			set
			{
				if ((this._SellPrice != value))
				{
					this.OnSellPriceChanging(value);
					this.SendPropertyChanging();
					this._SellPrice = value;
					this.SendPropertyChanged("SellPrice");
					this.OnSellPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Produk_DetailTrx", Storage="_DetailTrxes", ThisKey="ProdukId", OtherKey="ProdukId")]
		public EntitySet<DetailTrx> DetailTrxes
		{
			get
			{
				return this._DetailTrxes;
			}
			set
			{
				this._DetailTrxes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Produk_Promo", Storage="_Promos", ThisKey="ProdukId", OtherKey="ProdukId")]
		public EntitySet<Promo> Promos
		{
			get
			{
				return this._Promos;
			}
			set
			{
				this._Promos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DetailTrxes(DetailTrx entity)
		{
			this.SendPropertyChanging();
			entity.Produk = this;
		}
		
		private void detach_DetailTrxes(DetailTrx entity)
		{
			this.SendPropertyChanging();
			entity.Produk = null;
		}
		
		private void attach_Promos(Promo entity)
		{
			this.SendPropertyChanging();
			entity.Produk = this;
		}
		
		private void detach_Promos(Promo entity)
		{
			this.SendPropertyChanging();
			entity.Produk = null;
		}
	}
}
#pragma warning restore 1591
